### ISSUE TITLE
ffcreator build出来的镜像体积太大了，能精简下么？

### ISSUE THREAD

**Issue by lispking** [zdu-strong/Technical_Backup#3]
rt

**Comment by zdu-strong** [comment]
可以，你希望镜像里包含什么呢?
目前，不包含ffcreator的运行环境，包含仓库的全部代码和生成的测试视频文件.

**Comment by lispking** [comment]
希望这个包可以控制在3-500M左右，这样发布就比较友好

**Comment by zdu-strong** [comment]
Dockerfile文件位置:  [https://github.com/zdu-strong/Technical_Backup/blob/tmp/20230622/docker/default/ffcreator/Dockerfile](https://github.com/zdu-strong/Technical_Backup/blob/tmp/20230622/docker/default/ffcreator/Dockerfile)
大小: 256.3MB
内容:  包含ffcreator项目的代码和生成的测试视频.

**Comment by lispking** [comment]
这镜像是不合理的，运行的时候提示并没有node环境

**Comment by zdu-strong** [comment]
Dockerfile文件位置:  https://github.com/zdu-strong/Technical_Backup/blob/tmp/20230623/docker/default/ffcreator/Dockerfile
大小: 876.64MB
内容: 包含ffcreator项目的代码和运行环境

**Comment by lispking** [comment]
神奇了，mac m1环境下运行会提示webgl文件非法

```shell
Error: /home/app/node_modules/gl/build/Release/webgl.node: invalid ELF header
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at bindings (/home/app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/app/node_modules/gl/src/javascript/native-gl.js:1:40)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  code: 'ERR_DLOPEN_FAILED'
```

**Comment by zdu-strong** [comment]
一个悲伤的消息, 可以向gl仓库提交bug.
[https://github.com/stackgl/headless-gl](https://github.com/stackgl/headless-gl)

**Comment by zdu-strong** [comment]
请试试运行新分支，在Mac, 已升级gl依赖从v6.0.1至v6.0.2.

分支名称: tmp/20230625
Dockerfile文件位置:  https://github.com/zdu-strong/Technical_Backup/blob/tmp/20230625/docker/default/ffcreator/Dockerfile

**Comment by lispking** [comment]
这边测试效果还是一样，你那边有mac么？

**Comment by zdu-strong** [comment]
我没有一个mac.

**Comment by zdu-strong** [comment]
I will delete all temporary branches, if you need to test, please run the master branch.
